# -*- coding: utf-8 -*-
"""basic tirgram.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lna2Og7Obv2xd7sYLDja8bgCLVmsyRLI
"""

# Commented out IPython magic to ensure Python compatibility.
import math
import matplotlib.pyplot as plt
import numpy as np
# %matplotlib inline
import torch

words = open('names.txt', 'r').read().splitlines()

d={}
for w in words:
  w = '.'+ w + '.'
  for ch1,ch2,ch3 in zip(w,w[1:],w[2:]):
    if (ch1,ch2,ch3) not in d:
      d[(ch1,ch2,ch3)] = 0
    d[(ch1,ch2,ch3)] +=1
d= sorted(d.items(),key=lambda kv: -kv[1])

a=torch.zeros((27,27,27),dtype=torch.int32)

chars= sorted(list(set(''.join(words))))
chars.insert(0, '.')
stoi = {s:i for i,s in enumerate(chars)}
itos = {i:s for s,i in stoi.items()}

for w in words:
  ch = '.'+ w + '.'
  for ch1,ch2,ch3 in zip(ch,ch[1:],ch[2:]):
    i1=stoi[ch1]
    i2=stoi[ch2]
    i3=stoi[ch3]
    a[i1,i2,i3]+=1

from wordcloud import WordCloud
trigram_frequencies = {}
for i1 in range(len(chars)):
    for i2 in range(len(chars)):
        for i3 in range(len(chars)):
            count = a[i1, i2, i3].item()
            if count > 0:
                ch1 = itos[i1]
                ch2 = itos[i2]
                ch3 = itos[i3]
                trigram = ch1 + ch2 + ch3
                trigram_frequencies[trigram] = count
filtered_frequencies = {trigram: freq for trigram, freq in trigram_frequencies.items() if freq > 5}
wordcloud = WordCloud(width=800, height=400, background_color='white', colormap='plasma').generate_from_frequencies(filtered_frequencies)
plt.figure(figsize=(10, 5))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off")
plt.title('Word Cloud of Most Frequent Trigrams')
plt.show()

for i in range(10):
  ix=0
  out=[]
  while True:
    p=(a[:] + 1).float() # Add 1 for Laplace smoothing to prevent zero probabilities
    p/=p.sum(dim=2,keepdim=True)
    # Sample a single character (ch3) given ch1='.' (index 0) and ch2='.' (index 0)
    ix = torch.multinomial(p[0,0,:], num_samples=1, replacement=True)
    out.append(itos[ix.item()])
    if ix==0:
      break
  print(''.join(out))

p=(a[:] + 1).float()
p/=p.sum(dim=2,keepdim=True)

neg_log = 0.0
n=0
for w in words:
  ch = '.'+ w + '.'
  for ch1,ch2,ch3 in zip(ch,ch[1:],ch[2:]):
    i1=stoi[ch1]
    i2=stoi[ch2]
    i3=stoi[ch3]
    prob=p[i1,i2,i3]
    log_prob=torch.log(prob)
    neg_log+=-log_prob
    n+=1
neg_log/=n
print(float(neg_log))

"""NEURAL NETWORK FRAMEWORK"""

x,y = [],[]
for w in words:
  ch = '.'+ w + '.'
  for ch1,ch2,ch3 in zip(ch,ch[1:],ch[2:]):
    i1=stoi[ch1]
    i2=stoi[ch2]
    i3=stoi[ch3]
    x.append([i1,i2])
    y.append(i3)
x=torch.tensor(x)
y=torch.tensor(y)

import torch.nn.functional as F

g = torch.Generator()
w = torch.randn((27,27),requires_grad=True, generator=g)
b = torch.randn((27,),requires_grad=True, generator=g)
parameters = [w,b]

for k in range(50):
  xenc = F.one_hot(x,num_classes=27).float()
  input_for_linear = xenc.sum(dim=1)
  logits = input_for_linear @ w + b
  loss = F.cross_entropy(logits,y)
  for p in parameters:
    p.grad=None
  loss.backward()
  for p in parameters:
    p.data+= -10*p.grad
print(loss.item())

for _ in range(5):
  ix1 = 0
  ix2 = 0
  name_chars = []
  while True:
    x_current = torch.tensor([ix1, ix2])
    xenc_current = F.one_hot(x_current, num_classes=27).float()
    input_for_linear_current = xenc_current.sum(dim=0)
    logits = input_for_linear_current @ w + b
    counts=logits.exp()
    p=counts/counts.sum(dim=0,keepdim=True)
    ix = torch.multinomial(p, num_samples=1, replacement=True, generator=g).item()
    name_chars.append(itos[ix])
    ix1 = ix2
    ix2 = ix

    if ix == 0:
      break
  print(''.join(name_chars))

