# -*- coding: utf-8 -*-
"""MLP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18Ocnc2c7W9OPBp0vkR2PZvHyYZTP3zIU
"""

# Commented out IPython magic to ensure Python compatibility.
import math
import matplotlib as plt
import numpy as np
# %matplotlib inline

class Value:
  def __init__(self, data, _children = (), op =''):
    self.data=data
    self.grad = 0.0
    self._backward = lambda: None
    self._preview = set(_children)
    self._op = op
  def __repr__(self):
    return f"Value(data={self.data})"
  def __add__(self,other):
    other = other if isinstance(other, Value) else Value(other)
    out = Value(self.data + other.data, (self,other), '+')
    def _backward():
      self.grad += 1.0*out.grad
      other.grad += 1.0*out.grad
    out._backward = _backward
    return out
  def __mul__(self,other):
    other = other if isinstance(other, Value) else Value(other)
    out = Value(self.data * other.data, (self, other), '*')
    def _backward():
      self.grad += other.grad*out.grad
      other.grad += self.grad*out.grad
    out._backward = _backward
    return out
  def __rmul__(self,other):
    return self * other
  def __radd__(self,other):
    return self+ (-other)
  def __pow__(self,other):
    assert isinstance(other, (int, float))
    out = Value(self.data**other,(self,),f'**{other}')
    def _backward():
      self.grad +=other*(self.data)**(other-1)*out.grad
    out._backward=_backward
    return out
  def __truediv__(self,other):
    return self*other**(-1)
  def __neg__(self):
    return self*(-1)
  def __sub__(self,other):
    return self + (-other)
  def tanh(self):
    n = self.data
    t= (math.exp(2*n)-1)/(math.exp(2*n)+1)
    def _backward():
      self.grad += (1-t**2)*out.grad
    out =Value(t, (self,), 'tanh')
    out._backward = _backward
    return out
  def reLU(self):
    if self.data>0:
      out = Value(self, (self,), 'reLU')
    else:
      out = 0
    def _backward():
      if self.data>0:
        self.grad+=out.grad
      else:
        self.grad += 0
    return out
  def backward():
    topo=[]
    visited = set()
    def build_topo(v):
      if v not in visited:
        visited.add(v)
        for child in v._prev:
          build_topo(child)
        topo.appened(v)
    build_topo(self)
    self.grad = 1.0
    for node in reversed(topo):
      node._backward()

class Neuron:
  def __init__(self,nin):
    self.w= [Value(np.random.uniform(-1,1)) for i in range(nin)]
    self.b = Value(np.random.uniform(-1.1))
  def __call__(self, x):
    act = sum(wi*xi for wi, xi in zip(self.w,x)) + self.b
    out = act.tanh()
    return out
  def parameters(self):
    return self.w + [self.b]
class Layer:
  def __init__(self,nin,nout):
    self.neurons = [Neuron(nin) for i in range(nout)]
  def __call__(self,x):
    outs = [n(x) for n in self.neurons]
    return outs
    def parameters(self):
      return [p for neuron in self.neurons for p in neuron.parameters()]
class MLP:
  def __init__(self,nin, nouts):
    sz = [nin] + nouts
    self.layers = [Layer(sz[i],sz[i+1]) for i in range(len(nouts))]
  def __call__(self,x):
    for layer in self.layers:
      x = layer(x)
    return x
  def parameters(self):
    return [p for layer in self.layers for p in layer.parameters()]